export const FETCHING_LIST = 'FETCHING_LIST'
export const FETCHING_LIST_SUCCESS = 'FETCHING_LIST_SUCCESS'
export const FETCHING_LIST_FAILURE = 'FETCHING_LIST_FAILURE'

export const FETCHING_MOVIE_DETAILS = 'FETCHING_MOVIE_DETAILS'
export const FETCHING_MOVIE_DETAILS_SUCCESS = 'FETCHING_MOVIE_DETAILS_SUCCESS'
export const FETCHING_MOVIE_DETAILS_FAILURE = 'FETCHING_MOVIE_DETAILS_FAILURE'

export const IMAGE_BASE_URL = 'http://image.tmdb.org/t/p/w185'
export const IMAGE_BASE_URL_500 = 'http://image.tmdb.org/t/p/w500'
export const FETCHING_CAST_LIST = 'FETCHING_CAST_LIST'
export const FETCHING_CAST_LIST_SUCCESS = 'FETCHING_CAST_LIST_SUCCESS'
export const FETCHING_CAST_LIST_FAILURE = 'FETCHING_CAST_LIST_FAILURE'
export const API = 'FETCHING_CAST_LIST_FAILURE'

export const FETCHING_PEOPLE_IMAGE_LIST = 'FETCHING_PEOPLE_IMAGE_LIST'
export const FETCHING_PEOPLE_IMAGE_SUCCESS = 'FETCHING_PEOPLE_IMAGE_SUCCESS'
export const FETCHING_PEOPLE_IMAGE_FAILURE = 'FETCHING_PEOPLE_IMAGE_FAILURE'
